sample	coverage	taxonomy
sample_name	0.0780580175	d__Bacteria; p__Actinobacteriota; c__Coriobacteriia; o__Coriobacteriales; f__Atopobiaceae; g__Tractidigestivibacter; s__Tractidigestivibacter sp000752675
